URL <- "https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip"
download.file(URL,"hpc.zip")
unzip("hpc.zip")
hpc <- read.csv2("household_power_consumption.txt",na.strings = "?",stringsAsFactors = FALSE)
rel_hpc <- hpc[grep("^1/2/2007|^2/2/2007",hpc$Date),]
rel_hpc$Time <- strptime(paste(rel_hpc[,1],rel_hpc[,2],sep = " "), format = "%d/%m/%Y %T")
rel_hpc$Date <- as.Date(rel_hpc$Date, format = "%d/%m/%Y")
for(i in 3:9){rel_hpc[,i] <- as.numeric(rel_hpc[,i])}
png("plot4.png")
par(mfrow = c(2,2))
with(rel_hpc,plot(Time, Global_active_power, type = "n", xlab = "", ylab = "Global Active Power"))
with(rel_hpc,lines(Time, Global_active_power))
with(rel_hpc,plot(Time, Voltage, type = "n", xlab = "datetime", ylab = "Voltage"))
with(rel_hpc,lines(Time, Voltage))
with(rel_hpc,plot(Time, Sub_metering_1, type = "n", xlab = "", ylab = "Energy sub metering"))
with(rel_hpc,lines(Time, Sub_metering_1, col = "black"))
with(rel_hpc,lines(Time, Sub_metering_2, col = "red"))
with(rel_hpc,lines(Time, Sub_metering_3, col = "blue"))
legend("topright", legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c("black","red","blue"), lty = c(1,1,1))
with(rel_hpc,plot(Time, Global_reactive_power, type = "n", xlab = "datetime"))
with(rel_hpc,lines(Time,Global_reactive_power, lwd = 0.5))
dev.off()